version: "3.7"
services:
  registry:
    image: registry:2
    container_name: registry
    volumes: 
    - type: volume
      source: registry
      target: /var/lib/registry
    networks: 
      - registry
    ports:
      - "5000:5000"
    restart: always  

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    networks: 
      - registry
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_MODE_BROWSE_ONLY=true
    ports:
      - "8080:80"
    restart: always
    
volumes:
  registry:

networks:
  registry: