version: "3.7"
services:
  registry:
    image: registry:2
    container_name: registry
    volumes: 
    - type: volume
      source: registry
      target: /var/lib/registry
    - type: bind
      source: /home/projetos/certs
      target: /certs
    networks: 
      - registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/docker.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/docker.key
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    ports:
      - "443:443"
    restart: unless-stopped 

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    depends_on:
      - registry
    networks: 
      - registry
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=443
      - ENV_MODE_BROWSE_ONLY=true
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    ports:
      - "8080:80"
    restart: unless-stopped
    
volumes:
  registry:

networks:
  registry: